name=DeautherX-lib
version=0.1.1
author=BlackTechX
maintainer=BlackTechX
sentence=Unified ESP8266 Wi-Fi attack library. Deauth, Beacon, Probe, EvilTwin, Scanner.
paragraph=Pure C++ library for ESP8266 Deauther.
category=Communication
url=https://github.com/BlackTechX011/DeautherX-lib
architectures=esp8266
depends=DNSServer, ESP8266WiFi, ESP8266WebServer
